
@trafficImageUrl = https://api.data.gov.sg/v1/transport/traffic-images
@weatherForecast = https://api.data.gov.sg/v1/environment/2-hour-weather-forecast

@reverseMapping = https://www.onemap.gov.sg/api/public/revgeocode?location=1.384,103.891443&buffer=10&addressType=All&otherFeatures=N

@self = http://localhost:3005/trafficweather/
###
GET {{trafficImageUrl}}?date_time=2017-01-01T13:11:11

###
GET {{weatherForecast}} 

###
GET {{self}}2020-01-23T23:32:23 


